name: Deploy to Gitee Pages
description: This action will handle the deployment process of your project to Gitee Pages.
author: Yokefellow <yuan1241900094@gmail.com>
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'orange'
inputs:
  gitee_repo:
    description: SSH URL of the Gitee repo 
    required: true
  commit_message: 
    description: If you need to customize the commit message for an integration you can do so.
    required: false
    default: Commit from GitHub action
