name: Deploy to Gitee Pages
description: This action will handle the deployment process of your project to Gitee Pages.
author: Yokefellow <yuan1241900094@gmail.com>
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'orange'
inputs:
  gitee_repo:
    description: SSH URL of the Gitee repo
    required: true
  folder:
    description: The folder of GitHub Pages static files
    required: true
  git_user_email:
    description: The user.email of Git config
    required: true
  git_user_name:
    description: The user.name of Git config
    required: true
  cname:
    description: Set custom domain
    required: false
  gitee_pages_branch:
    description: The branch of Gitee Pages you want to push
    required: false
    default: master
  commit_message:
    description: If you need to customize the commit message for an integration you can do so.
    required: false
    default: Commit from GitHub Actions
