name: Deploy to Gitee Pages
description: This action will handle the deployment process of your project to Gitee Pages.
author: Yokefellow <yuan1241900094@gmail.com>
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'orange'
inputs:
  gitee_repo:
    description: SSH URL of the Gitee repo 
    required: true
  folder:
    description: The folder of GitHub Pages static files 
    required: true
  git_user_email:
    description: The email of Git global config 
    required: true
  git_user_name:
    description: The name of Git global config 
    required: true
  source_github_remote_branch:
    description: The GitHub remote branch of source code you pushed
    required: false
    default: gh-pages-source
  source_gitee_remote_branch:
    description: The Gitee remote branch of source code you want to push
    required: false
    default: gh-pages-source
  commit_message: 
    description: If you need to customize the commit message for an integration you can do so.
    required: false
    default: Commit from GitHub Actions
